### ISSUE TITLE
why is the bvh  upside down？

### ISSUE THREAD

**Issue by catalyster** [KosukeFukazawa/smpl2bvh#1]
Hi, thank you for the great work! And I want to know why my bvh converted from smpl is upside down? Do you have any solutions？

https://user-images.githubusercontent.com/53509756/188771181-169225ff-f0a2-4ad6-9f16-129d6b446fef.mp4

**Comment by KosukeFukazawa** [comment]
Hi, thank you for your feedback!
Perhaps the difference in coordinate systems may have an effect. (SMPL sets the y-axis upward and the z-axis forward.)
The motion itself does not seem to be broken, so it is possible that only the rotation of ROOT is odd.

**Comment by KosukeFukazawa** [comment]
A simple solution is to multiply a 180 degree rotation around the z-axis to the ROOT rotation.

**Comment by catalyster** [comment]
Yes, I multipled a180 degree rotation around the z-axis and y-axis to solve the problem temporarily.
