### ISSUE TITLE
different skeleton offsets got of repo smpl2bvh and CharacterAnimationTools

### ISSUE THREAD

**Issue by pangwong** [KosukeFukazawa/smpl2bvh#8]
Hi, I just found that on SMPL MALE model, the two of your projects got different skeleton offsets. I did not test on other SMPL models. I notice that the two projects use different methods to get the skeleton offsets. 
As offsets is critical to reconstruct the real body motion from joint rotations, the offsets difference may influence on  the final result motion, would you please tell why the difference happen and which method  is more reasonable ? thanks.

below are my results:
### by using smpl2bvh
```
python smpl2bvh.py --model_path models --poses gBR_sBM_cAll_d04_mBR0_ch01.pkl
 ```
printing offsets after [line](https://github.com/KosukeFukazawa/smpl2bvh/blob/08ca08d5cc41ab6d45e95cfbad919b14245bbf73/smpl2bvh.py#L96) I got
```
offsets:
[[ -0.21736789 -24.078918     2.8583794 ]
 [  5.858135    -8.228004    -1.7664082 ]
 [ -6.030973    -9.051326    -1.3542533 ]
 [  0.4439448   12.440356    -3.8385224 ]
 [  4.345143   -38.646942     0.80370027]
 [ -4.3256626  -38.368793    -0.48430422]
 [  0.4488444   13.795638     2.6820328 ]
 [ -1.4790334  -42.687447    -3.7428    ]
 [  1.9055545  -42.004562    -3.4561672 ]
 [ -0.22645919   5.603239     0.2855044 ]
 [  4.105436    -6.0286045   12.204244  ]
 [ -3.4839869   -6.2105536   13.03233   ]
 [ -1.3390183   21.163553    -3.3467577 ]
 [  7.1702466   11.399969    -1.889817  ]
 [ -8.295364    11.247234    -2.3707385 ]
 [  1.011321     8.893734     5.040986  ]
 [ 12.29214      4.520509    -1.9046001 ]
 [-11.32283      4.685326    -0.8472071 ]
 [ 25.533188    -1.5649021   -2.294649  ]
 [-26.01275     -1.4369264   -3.1268728 ]
 [ 26.570929     1.2698084   -0.73747337]
 [-26.910835     0.67937076  -0.60267633]
 [  8.669054    -1.0636002   -1.5594293 ]
 [ -8.87537     -0.86515695  -1.0107077 ]]
```

### by using CharacterAnimationTools,
```python
from anim import aistpp
anim: Animation = aistpp.load(
    aistpp_motion_path="gBR_sBM_cAll_d04_mBR0_ch01.pkl",
    smpl_path="models/smpl/SMPL_MALE.pkl"
)
```
printing offsets after [line](https://github.com/KosukeFukazawa/CharacterAnimationTools/blob/c9d366e4b61dc020634b26553faf1cdb00116bb1/anim/aistpp.py#L58) I got
```
offsets:
[[ -0.23178788 -25.67627446   3.04799966]
 [  6.24675465  -8.77383675  -1.88358908]
 [ -6.43105802  -9.65177882  -1.44409215]
 [  0.47339571  13.26562856  -4.09316365]
 [  4.6333931  -41.21072346   0.85701646]
 [ -4.61262024 -40.91411303  -0.51643223]
 [  0.47861966  14.71082034   2.85995446]
 [ -1.57715034 -45.51925651  -3.99109087]
 [  2.03196604 -44.79107482  -3.68544373]
 [ -0.24148185   5.97494929   0.30444463]
 [  4.37778461  -6.42852221  13.01385252]
 [ -3.71510957  -6.62255471  13.89687284]
 [ -1.42784683  22.56750892  -3.56877643]
 [  7.64591048  12.15622499  -2.01518469]
 [ -8.84566645  11.9933573   -2.52800977]
 [  1.07841059   9.48373246   5.37539715]
 [ 13.10757937   4.8203929   -2.03094816]
 [-12.07396959   4.99614436  -0.90340923]
 [ 27.227021    -1.66871601  -2.44687195]
 [-27.73839557  -1.5322525   -3.33430471]
 [ 28.33359887   1.3540481   -0.78639626]
 [-28.69606067   0.72444051  -0.64265731]
 [  9.24414583  -1.1341604   -1.66287925]
 [ -9.46415423  -0.92254989  -1.07775645]]
```

**Comment by KosukeFukazawa** [comment]
Hi pangwong,
Thank you for sharing the error!
The error was caused by multipling offsets to smpl_scaling in CharacterAnimationTools.
https://github.com/KosukeFukazawa/CharacterAnimationTools/blob/c9d366e4b61dc020634b26553faf1cdb00116bb1/anim/aistpp.py#L43
In contrast on [original aist++ repo](https://github.com/google-research/mint/blob/b8f8bdfbbe3fbfa67831a2ef9bcf71a6a9e74552/tools/preprocessing.py#L158), they only multiplied smpl_scaling to root trans.
smpl2bvh process is the correct one.

**Comment by pangwong** [comment]
Thank you for your quick reply,  I varified and now the results are same!
